// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9TkE4Mxqv8yzrpxN86x8MAjIiOO7cFM',
    appId: '1:960652309683:web:c1ee4a2378bd9c3fc3ecc6',
    messagingSenderId: '960652309683',
    projectId: 'global-nodes-assignment',
    authDomain: 'global-nodes-assignment.firebaseapp.com',
    storageBucket: 'global-nodes-assignment.appspot.com',
    measurementId: 'G-67F3F5PD8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4EvowdackoJJL7Lv0C49vri8USNsctkA',
    appId: '1:960652309683:android:07ec5089db2c87edc3ecc6',
    messagingSenderId: '960652309683',
    projectId: 'global-nodes-assignment',
    storageBucket: 'global-nodes-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC70ixzeyIBLXuEwYzV-VrxqqTYe8Bw-Y0',
    appId: '1:960652309683:ios:04271b94f0fe0a33c3ecc6',
    messagingSenderId: '960652309683',
    projectId: 'global-nodes-assignment',
    storageBucket: 'global-nodes-assignment.appspot.com',
    iosBundleId: 'com.flutterwings.globalNodesAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC70ixzeyIBLXuEwYzV-VrxqqTYe8Bw-Y0',
    appId: '1:960652309683:ios:e11ca630e52791fec3ecc6',
    messagingSenderId: '960652309683',
    projectId: 'global-nodes-assignment',
    storageBucket: 'global-nodes-assignment.appspot.com',
    iosBundleId: 'com.flutterwings.globalNodesAssignment.RunnerTests',
  );
}
